const hello = [
  {
    mainLanguages: 'Catalan, French and Portugese',
    sayHello: 'Catalan: Hola | French: Bonjour | Portugese: Ola',
    countryCode: 'AD',
    countryName: 'Andorra',
    currencyCode: 'EUR',
    population: '84000',
    fipsCode: 'AN',
    capital: 'Andorra la Vella',
    continentName: 'Europe',
    areaInSqKm: '468.0',
  },
  {
    mainLanguages: 'Arabic',
    sayHello: 'Salam',
    countryCode: 'AE',
    countryName: 'United Arab Emirates',
    currencyCode: 'AED',
    population: '4975593',
    fipsCode: 'AE',
    capital: 'Abu Dhabi',
    continentName: 'Asia',
    areaInSqKm: '82880.0',
  },
  {
    mainLanguages: 'Dari, Pashtu',
    sayHello: 'Dari: Salam | Pashtu: Salam',
    countryCode: 'AF',
    countryName: 'Afghanistan',
    currencyCode: 'AFN',
    population: '29121286',
    fipsCode: 'AF',
    capital: 'Kabul',
    continentName: 'Asia',
    areaInSqKm: '647500.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'AG',
    countryName: 'Antigua and Barbuda',
    currencyCode: 'XCD',
    population: '86754',
    fipsCode: 'AC',
    capital: "St. John's",
    continentName: 'North America',
    areaInSqKm: '443.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'AI',
    countryName: 'Anguilla',
    currencyCode: 'XCD',
    population: '13254',
    fipsCode: 'AV',
    capital: 'The Valley',
    continentName: 'North America',
    areaInSqKm: '102.0',
  },
  {
    mainLanguages: 'Albanian, Greek',
    sayHello: "Albanian: C'kemi  | Greek: Ya ",
    countryCode: 'AL',
    countryName: 'Albania',
    currencyCode: 'ALL',
    population: '2986952',
    fipsCode: 'AL',
    capital: 'Tirana',
    continentName: 'Europe',
    areaInSqKm: '28748.0',
  },
  {
    mainLanguages: 'Armenian',
    sayHello: 'Alló',
    countryCode: 'AM',
    countryName: 'Armenia',
    currencyCode: 'AMD',
    population: '2968000',
    fipsCode: 'AM',
    capital: 'Yerevan',
    continentName: 'Asia',
    areaInSqKm: '29800.0',
  },
  {
    mainLanguages: 'Portugese',
    sayHello: 'Olá',
    countryCode: 'AO',
    countryName: 'Angola',
    currencyCode: 'AOA',
    population: '13068161',
    fipsCode: 'AO',
    capital: 'Luanda',
    continentName: 'Africa',
    areaInSqKm: '1246700.0',
  },
  {
    mainLanguages: 'Penguinese',
    sayHello: 'Squak!',
    countryCode: 'AQ',
    countryName: 'Antarctica',
    currencyCode: '',
    population: '0',
    fipsCode: 'AY',
    capital: '',
    continentName: 'Antarctica',
    areaInSqKm: '1.4E7',
  },
  {
    mainLanguages: 'Spanish',
    sayHello: 'Hola',
    countryCode: 'AR',
    countryName: 'Argentina',
    currencyCode: 'ARS',
    population: '41343201',
    fipsCode: 'AR',
    capital: 'Buenos Aires',
    continentName: 'South America',
    areaInSqKm: '2766890.0',
  },
  {
    mainLanguages: 'English, Samoan',
    sayHello: 'English: Hello | Samoan: Talofa',
    countryCode: 'AS',
    countryName: 'American Samoa',
    currencyCode: 'USD',
    population: '57881',
    fipsCode: 'AQ',
    capital: 'Pago Pago',
    continentName: 'Oceania',
    areaInSqKm: '199.0',
  },
  {
    mainLanguages: 'German',
    sayHello: 'Servus',
    countryCode: 'AT',
    countryName: 'Austria',
    currencyCode: 'EUR',
    population: '8205000',
    fipsCode: 'AU',
    capital: 'Vienna',
    continentName: 'Europe',
    areaInSqKm: '83858.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'AU',
    countryName: 'Australia',
    currencyCode: 'AUD',
    population: '21515754',
    fipsCode: 'AS',
    capital: 'Canberra',
    continentName: 'Oceania',
    areaInSqKm: '7686850.0',
  },
  {
    mainLanguages: 'Dutch, Papiamento',
    sayHello: 'Dutch: Hallo or Goedendag(informal) | Papiamento: Bon dia',
    countryCode: 'AW',
    countryName: 'Aruba',
    currencyCode: 'AWG',
    population: '71566',
    fipsCode: 'AA',
    capital: 'Oranjestad',
    continentName: 'North America',
    areaInSqKm: '193.0',
  },
  {
    mainLanguages: 'Swedish',
    sayHello: 'God dag(formal), Hej(informal)',
    countryCode: 'AX',
    countryName: 'Åland',
    currencyCode: 'EUR',
    population: '26711',
    fipsCode: '',
    capital: 'Mariehamn',
    continentName: 'Europe',
    areaInSqKm: '1580.0',
  },
  {
    mainLanguages: 'Azerbaijani Turkic',
    sayHello: 'Salam',
    countryCode: 'AZ',
    countryName: 'Azerbaijan',
    currencyCode: 'AZN',
    population: '8303512',
    fipsCode: 'AJ',
    capital: 'Baku',
    continentName: 'Asia',
    areaInSqKm: '86600.0',
  },
  {
    mainLanguages: 'Bosnian, Coratian, Serbian',
    sayHello: 'Bosnian: Dobar dan(formal) Zdravo(informal) | Croatian: Bok | Serbian: Zdravo',
    countryCode: 'BA',
    countryName: 'Bosnia and Herzegovina',
    currencyCode: 'BAM',
    population: '4590000',
    fipsCode: 'BK',
    capital: 'Sarajevo',
    continentName: 'Europe',
    areaInSqKm: '51129.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'BB',
    countryName: 'Barbados',
    currencyCode: 'BBD',
    population: '285653',
    fipsCode: 'BB',
    capital: 'Bridgetown',
    continentName: 'North America',
    areaInSqKm: '431.0',
  },
  {
    mainLanguages: 'Bengali',
    sayHello: 'Hyālō',
    countryCode: 'BD',
    countryName: 'Bangladesh',
    currencyCode: 'BDT',
    population: '156118464',
    fipsCode: 'BG',
    capital: 'Dhaka',
    continentName: 'Asia',
    areaInSqKm: '144000.0',
  },
  {
    mainLanguages: 'Dutch, French, German',
    sayHello: 'Dutch: Hallo(formal) Goededag(informal) | French: Bonjour(formal) Salut(informal) | German: Guten Tag',
    countryCode: 'BE',
    countryName: 'Belgium',
    currencyCode: 'EUR',
    population: '10403000',
    fipsCode: 'BE',
    capital: 'Brussels',
    continentName: 'Europe',
    areaInSqKm: '30510.0',
  },
  {
    mainLanguages: 'French',
    sayHello: 'French: Bonjour(formal) Salut(informal)',
    countryCode: 'BF',
    countryName: 'Burkina Faso',
    currencyCode: 'XOF',
    population: '16241811',
    fipsCode: 'UV',
    capital: 'Ouagadougou',
    continentName: 'Africa',
    areaInSqKm: '274200.0',
  },
  {
    mainLanguages: 'Bulgarian',
    sayHello: 'Alo(formal) Docuvane(informal)',
    countryCode: 'BG',
    countryName: 'Bulgaria',
    currencyCode: 'BGN',
    population: '7148785',
    fipsCode: 'BU',
    capital: 'Sofia',
    continentName: 'Europe',
    areaInSqKm: '110910.0',
  },
  {
    mainLanguages: 'Arabic',
    sayHello: 'Salam',
    countryCode: 'BH',
    countryName: 'Bahrain',
    currencyCode: 'BHD',
    population: '738004',
    fipsCode: 'BA',
    capital: 'Manama',
    continentName: 'Asia',
    areaInSqKm: '665.0',
  },
  {
    mainLanguages: 'Kirundi, French, Swahili',
    sayHello: 'Kirundi: Bwakeye | French: Salut | Swahili: Jambo/Salama',
    countryCode: 'BI',
    countryName: 'Burundi',
    currencyCode: 'BIF',
    population: '9863117',
    fipsCode: 'BY',
    capital: 'Bujumbura',
    continentName: 'Africa',
    areaInSqKm: '27830.0',
  },
  {
    mainLanguages: 'French, Fon, Youruba',
    sayHello: 'French: Salut | Fon: Kudeu | Yoruba: Ẹ n lẹ (pronounced: EN-leh)',
    countryCode: 'BJ',
    countryName: 'Benin',
    currencyCode: 'XOF',
    population: '9056010',
    fipsCode: 'BN',
    capital: 'Porto-Novo',
    continentName: 'Africa',
    areaInSqKm: '112620.0',
  },
  {
    mainLanguages: 'French',
    sayHello: 'Salut',
    countryCode: 'BL',
    countryName: 'Saint Barthélemy',
    currencyCode: 'EUR',
    population: '8450',
    fipsCode: 'TB',
    capital: 'Gustavia',
    continentName: 'North America',
    areaInSqKm: '21.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'BM',
    countryName: 'Bermuda',
    currencyCode: 'BMD',
    population: '65365',
    fipsCode: 'BD',
    capital: 'Hamilton',
    continentName: 'North America',
    areaInSqKm: '53.0',
  },
  {
    mainLanguages: 'Malay, English',
    sayHello: 'Malay: Selamat pagi | English: Hello',
    countryCode: 'BN',
    countryName: 'Brunei',
    currencyCode: 'BND',
    population: '395027',
    fipsCode: 'BX',
    capital: 'Bandar Seri Begawan',
    continentName: 'Asia',
    areaInSqKm: '5770.0',
  },
  {
    mainLanguages: 'Spanish, Quechua, Aymara',
    sayHello: 'Spanish: Hola | Quechua: Rimaykullayki | Aymara: Kamisaraki',
    countryCode: 'BO',
    countryName: 'Bolivia',
    currencyCode: 'BOB',
    population: '9947418',
    fipsCode: 'BL',
    capital: 'Sucre',
    continentName: 'South America',
    areaInSqKm: '1098580.0',
  },
  {
    mainLanguages: 'Dutch, Papiamentu',
    sayHello: 'Dutch: Goededag | Papiamentu: Bon dia',
    countryCode: 'BQ',
    countryName: 'Bonaire',
    currencyCode: 'USD',
    population: '18012',
    fipsCode: '',
    capital: 'Kralendijk',
    continentName: 'North America',
    areaInSqKm: '328.0',
  },
  {
    mainLanguages: 'Portugese',
    sayHello: 'Ola',
    countryCode: 'BR',
    countryName: 'Brazil',
    currencyCode: 'BRL',
    population: '201103330',
    fipsCode: 'BR',
    capital: 'Brasília',
    continentName: 'South America',
    areaInSqKm: '8511965.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'BS',
    countryName: 'Bahamas',
    currencyCode: 'BSD',
    population: '301790',
    fipsCode: 'BF',
    capital: 'Nassau',
    continentName: 'North America',
    areaInSqKm: '13940.0',
  },
  {
    mainLanguages: 'Dzongkha',
    sayHello: 'Kuzu zangpo',
    countryCode: 'BT',
    countryName: 'Bhutan',
    currencyCode: 'BTN',
    population: '699847',
    fipsCode: 'BT',
    capital: 'Thimphu',
    continentName: 'Asia',
    areaInSqKm: '47000.0',
  },
  {
    mainLanguages: 'Penguinese',
    sayHello: 'Squak!',
    countryCode: 'BV',
    countryName: 'Bouvet Island',
    currencyCode: 'NOK',
    population: '0',
    fipsCode: 'BV',
    capital: '',
    continentName: 'Antarctica',
    areaInSqKm: '49.0',
  },
  {
    mainLanguages: 'Setswana',
    sayHello: 'Dumela',
    countryCode: 'BW',
    countryName: 'Botswana',
    currencyCode: 'BWP',
    population: '2029307',
    fipsCode: 'BC',
    capital: 'Gaborone',
    continentName: 'Africa',
    areaInSqKm: '600370.0',
  },
  {
    mainLanguages: 'Belorussian',
    sayHello: 'Vitaju',
    countryCode: 'BY',
    countryName: 'Belarus',
    currencyCode: 'BYR',
    population: '9685000',
    fipsCode: 'BO',
    capital: 'Minsk',
    continentName: 'Europe',
    areaInSqKm: '207600.0',
  },
  {
    mainLanguages: 'English, Spanish,',
    sayHello: 'Eglish: Hello | Spanish: Hola',
    countryCode: 'BZ',
    countryName: 'Belize',
    currencyCode: 'BZD',
    population: '314522',
    fipsCode: 'BH',
    capital: 'Belmopan',
    continentName: 'North America',
    areaInSqKm: '22966.0',
  },
  {
    mainLanguages: 'English, French',
    sayHello: 'English: Hello | French: Bonjour(formal), Salut(informal)',
    countryCode: 'CA',
    countryName: 'Canada',
    currencyCode: 'CAD',
    population: '33679000',
    fipsCode: 'CA',
    capital: 'Ottawa',
    continentName: 'North America',
    areaInSqKm: '9984670.0',
  },
  {
    mainLanguages: 'English, Malay',
    sayHello: 'English: Hello | Malay: Selamat pagi ',
    countryCode: 'CC',
    countryName: 'Cocos [Keeling] Islands',
    currencyCode: 'AUD',
    population: '628',
    fipsCode: 'CK',
    capital: 'West Island',
    continentName: 'Asia',
    areaInSqKm: '14.0',
  },
  {
    mainLanguages: 'French, Lingala',
    sayHello: 'French: Bonjour(formal), Salut(informal) | Lingala: Mbote ',
    countryCode: 'CD',
    countryName: 'Democratic Republic of the Congo',
    currencyCode: 'CDF',
    population: '70916439',
    fipsCode: 'CG',
    capital: 'Kinshasa',
    continentName: 'Africa',
    areaInSqKm: '2345410.0',
  },
  {
    mainLanguages: 'French, Sangho',
    sayHello: 'French: Bonjour(formal), Salut(informal) | Sangho: Balao ',
    countryCode: 'CF',
    countryName: 'Central African Republic',
    currencyCode: 'XAF',
    population: '4844927',
    fipsCode: 'CT',
    capital: 'Bangui',
    continentName: 'Africa',
    areaInSqKm: '622984.0',
  },
  {
    mainLanguages: 'French, Lingala',
    sayHello: 'French: Bonjour(formal), Salut(informal) | Lingala: Mbote',
    countryCode: 'CG',
    countryName: 'Republic of the Congo',
    currencyCode: 'XAF',
    population: '3039126',
    fipsCode: 'CF',
    capital: 'Brazzaville',
    continentName: 'Africa',
    areaInSqKm: '342000.0',
  },
  {
    mainLanguages: 'Swiss German, French',
    sayHello: 'Swiss German: Sali | French: Bonjour(formal), Salut(informal)',
    countryCode: 'CH',
    countryName: 'Switzerland',
    currencyCode: 'CHF',
    population: '7581000',
    fipsCode: 'SZ',
    capital: 'Bern',
    continentName: 'Europe',
    areaInSqKm: '41290.0',
  },
  {
    mainLanguages: 'French',
    sayHello: 'Salut',
    countryCode: 'CI',
    countryName: 'Ivory Coast',
    currencyCode: 'XOF',
    population: '21058798',
    fipsCode: 'IV',
    capital: 'Yamoussoukro',
    continentName: 'Africa',
    areaInSqKm: '322460.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'CK',
    countryName: 'Cook Islands',
    currencyCode: 'NZD',
    population: '21388',
    fipsCode: 'CW',
    capital: 'Avarua',
    continentName: 'Oceania',
    areaInSqKm: '240.0',
  },
  {
    mainLanguages: 'Spanish',
    sayHello: 'Olá',
    countryCode: 'CL',
    countryName: 'Chile',
    currencyCode: 'CLP',
    population: '16746491',
    fipsCode: 'CI',
    capital: 'Santiago',
    continentName: 'South America',
    areaInSqKm: '756950.0',
  },
  {
    mainLanguages: 'French, English',
    sayHello: 'French: Salut | English: Hello',
    countryCode: 'CM',
    countryName: 'Cameroon',
    currencyCode: 'XAF',
    population: '19294149',
    fipsCode: 'CM',
    capital: 'Yaoundé',
    continentName: 'Africa',
    areaInSqKm: '475440.0',
  },
  {
    mainLanguages: 'Standard Chinese (Mandarin/Putonghua), Yue (Cantonese)',
    sayHello: 'Mandarin: Nǐ hǎo | Cantonese: Néih hóu',
    countryCode: 'CN',
    countryName: 'China',
    currencyCode: 'CNY',
    population: '1330044000',
    fipsCode: 'CH',
    capital: 'Beijing',
    continentName: 'Asia',
    areaInSqKm: '9596960.0',
  },
  {
    mainLanguages: 'Spanish',
    sayHello: 'Olá',
    countryCode: 'CO',
    countryName: 'Colombia',
    currencyCode: 'COP',
    population: '47790000',
    fipsCode: 'CO',
    capital: 'Bogotá',
    continentName: 'South America',
    areaInSqKm: '1138910.0',
  },
  {
    mainLanguages: 'Spanish',
    sayHello: 'Olá',
    countryCode: 'CR',
    countryName: 'Costa Rica',
    currencyCode: 'CRC',
    population: '4516220',
    fipsCode: 'CS',
    capital: 'San José',
    continentName: 'North America',
    areaInSqKm: '51100.0',
  },
  {
    mainLanguages: 'Spanish',
    sayHello: 'Olá',
    countryCode: 'CU',
    countryName: 'Cuba',
    currencyCode: 'CUP',
    population: '11423000',
    fipsCode: 'CU',
    capital: 'Havana',
    continentName: 'North America',
    areaInSqKm: '110860.0',
  },
  {
    mainLanguages: 'Portugese',
    sayHello: 'Olá',
    countryCode: 'CV',
    countryName: 'Cape Verde',
    currencyCode: 'CVE',
    population: '508659',
    fipsCode: 'CV',
    capital: 'Praia',
    continentName: 'Africa',
    areaInSqKm: '4033.0',
  },
  {
    mainLanguages: 'Dutch',
    sayHello: 'Hallo',
    countryCode: 'CW',
    countryName: 'Curacao',
    currencyCode: 'ANG',
    population: '141766',
    fipsCode: 'UC',
    capital: 'Willemstad',
    continentName: 'North America',
    areaInSqKm: '444.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'CX',
    countryName: 'Christmas Island',
    currencyCode: 'AUD',
    population: '1500',
    fipsCode: 'KT',
    capital: 'Flying Fish Cove',
    continentName: 'Asia',
    areaInSqKm: '135.0',
  },
  {
    mainLanguages: 'Greek, Turkish ',
    sayHello: 'Greek: Ya | Turkish: Selam/Merhaba',
    countryCode: 'CY',
    countryName: 'Cyprus',
    currencyCode: 'EUR',
    population: '1102677',
    fipsCode: 'CY',
    capital: 'Nicosia',
    continentName: 'Europe',
    areaInSqKm: '9250.0',
  },
  {
    mainLanguages: 'Czech',
    sayHello: 'Haló',
    countryCode: 'CZ',
    countryName: 'Czech Republic',
    currencyCode: 'CZK',
    population: '10476000',
    fipsCode: 'EZ',
    capital: 'Prague',
    continentName: 'Europe',
    areaInSqKm: '78866.0',
  },
  {
    mainLanguages: 'German',
    sayHello: 'Hallo',
    countryCode: 'DE',
    countryName: 'Germany',
    currencyCode: 'EUR',
    population: '81802257',
    fipsCode: 'GM',
    capital: 'Berlin',
    continentName: 'Europe',
    areaInSqKm: '357021.0',
  },
  {
    mainLanguages: 'French, Arabic',
    sayHello: 'French: Salut | Arabic: Salam',
    countryCode: 'DJ',
    countryName: 'Djibouti',
    currencyCode: 'DJF',
    population: '740528',
    fipsCode: 'DJ',
    capital: 'Djibouti',
    continentName: 'Africa',
    areaInSqKm: '23000.0',
  },
  {
    mainLanguages: 'Danish',
    sayHello: 'Hej',
    countryCode: 'DK',
    countryName: 'Denmark',
    currencyCode: 'DKK',
    population: '5484000',
    fipsCode: 'DA',
    capital: 'Copenhagen',
    continentName: 'Europe',
    areaInSqKm: '43094.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'DM',
    countryName: 'Dominica',
    currencyCode: 'XCD',
    population: '72813',
    fipsCode: 'DO',
    capital: 'Roseau',
    continentName: 'North America',
    areaInSqKm: '754.0',
  },
  {
    mainLanguages: 'Spanish',
    sayHello: '¡Hola!',
    countryCode: 'DO',
    countryName: 'Dominican Republic',
    currencyCode: 'DOP',
    population: '9823821',
    fipsCode: 'DR',
    capital: 'Santo Domingo',
    continentName: 'North America',
    areaInSqKm: '48730.0',
  },
  {
    mainLanguages: 'Arabic',
    sayHello: 'Salam',
    countryCode: 'DZ',
    countryName: 'Algeria',
    currencyCode: 'DZD',
    population: '34586184',
    fipsCode: 'AG',
    capital: 'Algiers',
    continentName: 'Africa',
    areaInSqKm: '2381740.0',
  },
  {
    mainLanguages: 'Spanish',
    sayHello: '¡Hola!',
    countryCode: 'EC',
    countryName: 'Ecuador',
    currencyCode: 'USD',
    population: '14790608',
    fipsCode: 'EC',
    capital: 'Quito',
    continentName: 'South America',
    areaInSqKm: '283560.0',
  },
  {
    mainLanguages: 'Estonian',
    sayHello: 'Tere',
    countryCode: 'EE',
    countryName: 'Estonia',
    currencyCode: 'EUR',
    population: '1291170',
    fipsCode: 'EN',
    capital: 'Tallinn',
    continentName: 'Europe',
    areaInSqKm: '45226.0',
  },
  {
    mainLanguages: 'Arabic',
    sayHello: 'Salam',
    countryCode: 'EG',
    countryName: 'Egypt',
    currencyCode: 'EGP',
    population: '80471869',
    fipsCode: 'EG',
    capital: 'Cairo',
    continentName: 'Africa',
    areaInSqKm: '1001450.0',
  },
  {
    mainLanguages: 'Arabic',
    sayHello: 'Salam',
    countryCode: 'EH',
    countryName: 'Western Sahara',
    currencyCode: 'MAD',
    population: '273008',
    fipsCode: 'WI',
    capital: 'Laâyoune / El Aaiún',
    continentName: 'Africa',
    areaInSqKm: '266000.0',
  },
  {
    mainLanguages: 'Tigrinya',
    sayHello: 'Selam',
    countryCode: 'ER',
    countryName: 'Eritrea',
    currencyCode: 'ERN',
    population: '5792984',
    fipsCode: 'ER',
    capital: 'Asmara',
    continentName: 'Africa',
    areaInSqKm: '121320.0',
  },
  {
    mainLanguages: 'Spanish',
    sayHello: '¡Hola!',
    countryCode: 'ES',
    countryName: 'Spain',
    currencyCode: 'EUR',
    population: '46505963',
    fipsCode: 'SP',
    capital: 'Madrid',
    continentName: 'Europe',
    areaInSqKm: '504782.0',
  },
  {
    mainLanguages: 'Amharic',
    sayHello: 'Salam',
    countryCode: 'ET',
    countryName: 'Ethiopia',
    currencyCode: 'ETB',
    population: '88013491',
    fipsCode: 'ET',
    capital: 'Addis Ababa',
    continentName: 'Africa',
    areaInSqKm: '1127127.0',
  },
  {
    mainLanguages: 'Finnish',
    sayHello: 'Terve',
    countryCode: 'FI',
    countryName: 'Finland',
    currencyCode: 'EUR',
    population: '5244000',
    fipsCode: 'FI',
    capital: 'Helsinki',
    continentName: 'Europe',
    areaInSqKm: '337030.0',
  },
  {
    mainLanguages: 'English, Fijian',
    sayHello: 'English: Hello | Fijian: Bula ',
    countryCode: 'FJ',
    countryName: 'Fiji',
    currencyCode: 'FJD',
    population: '875983',
    fipsCode: 'FJ',
    capital: 'Suva',
    continentName: 'Oceania',
    areaInSqKm: '18270.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'FK',
    countryName: 'Falkland Islands',
    currencyCode: 'FKP',
    population: '2638',
    fipsCode: 'FK',
    capital: 'Stanley',
    continentName: 'South America',
    areaInSqKm: '12173.0',
  },
  {
    mainLanguages: "It's a group of islands!",
    sayHello: 'Try looking up a specific country',
    countryCode: 'FM',
    countryName: 'Micronesia',
    currencyCode: 'USD',
    population: '107708',
    fipsCode: 'FM',
    capital: 'Palikir',
    continentName: 'Oceania',
    areaInSqKm: '702.0',
  },
  {
    mainLanguages: 'Faroese, Danish',
    sayHello: 'Faroese: Hallo/Hey | Danish: Hallo ',
    countryCode: 'FO',
    countryName: 'Faroe Islands',
    currencyCode: 'DKK',
    population: '48228',
    fipsCode: 'FO',
    capital: 'Tórshavn',
    continentName: 'Europe',
    areaInSqKm: '1399.0',
  },
  {
    mainLanguages: 'French',
    sayHello: 'Salut',
    countryCode: 'FR',
    countryName: 'France',
    currencyCode: 'EUR',
    population: '64768389',
    fipsCode: 'FR',
    capital: 'Paris',
    continentName: 'Europe',
    areaInSqKm: '547030.0',
  },
  {
    mainLanguages: 'French',
    sayHello: 'Salut',
    countryCode: 'GA',
    countryName: 'Gabon',
    currencyCode: 'XAF',
    population: '1545255',
    fipsCode: 'GB',
    capital: 'Libreville',
    continentName: 'Africa',
    areaInSqKm: '267667.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'GB',
    countryName: 'United Kingdom',
    currencyCode: 'GBP',
    population: '62348447',
    fipsCode: 'UK',
    capital: 'London',
    continentName: 'Europe',
    areaInSqKm: '244820.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'GD',
    countryName: 'Grenada',
    currencyCode: 'XCD',
    population: '107818',
    fipsCode: 'GJ',
    capital: "St. George's",
    continentName: 'North America',
    areaInSqKm: '344.0',
  },
  {
    mainLanguages: 'Georgian',
    sayHello: 'Alo',
    countryCode: 'GE',
    countryName: 'Georgia',
    currencyCode: 'GEL',
    population: '4630000',
    fipsCode: 'GG',
    capital: 'Tbilisi',
    continentName: 'Asia',
    areaInSqKm: '69700.0',
  },
  {
    mainLanguages: 'French',
    sayHello: 'Salut',
    countryCode: 'GF',
    countryName: 'French Guiana',
    currencyCode: 'EUR',
    population: '195506',
    fipsCode: 'FG',
    capital: 'Cayenne',
    continentName: 'South America',
    areaInSqKm: '91000.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'GG',
    countryName: 'Guernsey',
    currencyCode: 'GBP',
    population: '65228',
    fipsCode: 'GK',
    capital: 'St Peter Port',
    continentName: 'Europe',
    areaInSqKm: '78.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'GH',
    countryName: 'Ghana',
    currencyCode: 'GHS',
    population: '24339838',
    fipsCode: 'GH',
    capital: 'Accra',
    continentName: 'Africa',
    areaInSqKm: '239460.0',
  },
  {
    mainLanguages: 'English, Spanish',
    sayHello: 'English: Hello | Spanish: ¡Hola!',
    countryCode: 'GI',
    countryName: 'Gibraltar',
    currencyCode: 'GIP',
    population: '27884',
    fipsCode: 'GI',
    capital: 'Gibraltar',
    continentName: 'Europe',
    areaInSqKm: '6.5',
  },
  {
    mainLanguages: 'Greenlandic',
    sayHello: 'Aluu',
    countryCode: 'GL',
    countryName: 'Greenland',
    currencyCode: 'DKK',
    population: '56375',
    fipsCode: 'GL',
    capital: 'Nuuk',
    continentName: 'North America',
    areaInSqKm: '2166086.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'GM',
    countryName: 'Gambia',
    currencyCode: 'GMD',
    population: '1593256',
    fipsCode: 'GA',
    capital: 'Bathurst',
    continentName: 'Africa',
    areaInSqKm: '11300.0',
  },
  {
    mainLanguages: 'French',
    sayHello: 'Salut',
    countryCode: 'GN',
    countryName: 'Guinea',
    currencyCode: 'GNF',
    population: '10324025',
    fipsCode: 'GV',
    capital: 'Conakry',
    continentName: 'Africa',
    areaInSqKm: '245857.0',
  },
  {
    mainLanguages: 'French',
    sayHello: 'Salut',
    countryCode: 'GP',
    countryName: 'Guadeloupe',
    currencyCode: 'EUR',
    population: '443000',
    fipsCode: 'GP',
    capital: 'Basse-Terre',
    continentName: 'North America',
    areaInSqKm: '1780.0',
  },
  {
    mainLanguages: 'Spanish, French',
    sayHello: 'Spanish: Hola | French: Salut',
    countryCode: 'GQ',
    countryName: 'Equatorial Guinea',
    currencyCode: 'XAF',
    population: '1014999',
    fipsCode: 'EK',
    capital: 'Malabo',
    continentName: 'Africa',
    areaInSqKm: '28051.0',
  },
  {
    mainLanguages: 'Greek',
    sayHello: 'Ya',
    countryCode: 'GR',
    countryName: 'Greece',
    currencyCode: 'EUR',
    population: '11000000',
    fipsCode: 'GR',
    capital: 'Athens',
    continentName: 'Europe',
    areaInSqKm: '131940.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'GS',
    countryName: 'South Georgia and the South Sandwich Islands',
    currencyCode: 'GBP',
    population: '30',
    fipsCode: 'SX',
    capital: 'Grytviken',
    continentName: 'Antarctica',
    areaInSqKm: '3903.0',
  },
  {
    mainLanguages: 'Spanish, French',
    sayHello: 'Spanish: Hola | French: Salut',
    countryCode: 'GT',
    countryName: 'Guatemala',
    currencyCode: 'GTQ',
    population: '13550440',
    fipsCode: 'GT',
    capital: 'Guatemala City',
    continentName: 'North America',
    areaInSqKm: '108890.0',
  },
  {
    mainLanguages: 'English, Chamorro',
    sayHello: 'English: Hello | Chamorro: Håfa ådai',
    countryCode: 'GU',
    countryName: 'Guam',
    currencyCode: 'USD',
    population: '159358',
    fipsCode: 'GQ',
    capital: 'Hagåtña',
    continentName: 'Oceania',
    areaInSqKm: '549.0',
  },
  {
    mainLanguages: 'Portugese',
    sayHello: 'Olá',
    countryCode: 'GW',
    countryName: 'Guinea-Bissau',
    currencyCode: 'XOF',
    population: '1565126',
    fipsCode: 'PU',
    capital: 'Bissau',
    continentName: 'Africa',
    areaInSqKm: '36120.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'GY',
    countryName: 'Guyana',
    currencyCode: 'GYD',
    population: '748486',
    fipsCode: 'GY',
    capital: 'Georgetown',
    continentName: 'South America',
    areaInSqKm: '214970.0',
  },
  {
    mainLanguages: 'Cantonese',
    sayHello: 'Néih hóu',
    countryCode: 'HK',
    countryName: 'Hong Kong',
    currencyCode: 'HKD',
    population: '6898686',
    fipsCode: 'HK',
    capital: 'Hong Kong',
    continentName: 'Asia',
    areaInSqKm: '1092.0',
  },
  {
    mainLanguages: 'Penguinese',
    sayHello: 'Squak! Squak!',
    countryCode: 'HM',
    countryName: 'Heard Island and McDonald Islands',
    currencyCode: 'AUD',
    population: '0',
    fipsCode: 'HM',
    capital: '',
    continentName: 'Antarctica',
    areaInSqKm: '412.0',
  },
  {
    mainLanguages: 'Spanish',
    sayHello: 'Hola',
    countryCode: 'HN',
    countryName: 'Honduras',
    currencyCode: 'HNL',
    population: '7989415',
    fipsCode: 'HO',
    capital: 'Tegucigalpa',
    continentName: 'North America',
    areaInSqKm: '112090.0',
  },
  {
    mainLanguages: 'Croatian',
    sayHello: 'Bok',
    countryCode: 'HR',
    countryName: 'Croatia',
    currencyCode: 'HRK',
    population: '4491000',
    fipsCode: 'HR',
    capital: 'Zagreb',
    continentName: 'Europe',
    areaInSqKm: '56542.0',
  },
  {
    mainLanguages: 'French, Haitian Creole',
    sayHello: 'French: Salut | Haitian Creole: Alo',
    countryCode: 'HT',
    countryName: 'Haiti',
    currencyCode: 'HTG',
    population: '9648924',
    fipsCode: 'HA',
    capital: 'Port-au-Prince',
    continentName: 'North America',
    areaInSqKm: '27750.0',
  },
  {
    mainLanguages: 'Hungarian',
    sayHello: 'Halló',
    countryCode: 'HU',
    countryName: 'Hungary',
    currencyCode: 'HUF',
    population: '9982000',
    fipsCode: 'HU',
    capital: 'Budapest',
    continentName: 'Europe',
    areaInSqKm: '93030.0',
  },
  {
    mainLanguages: 'Indonesian',
    sayHello: 'Halo',
    countryCode: 'ID',
    countryName: 'Indonesia',
    currencyCode: 'IDR',
    population: '242968342',
    fipsCode: 'ID',
    capital: 'Jakarta',
    continentName: 'Asia',
    areaInSqKm: '1919440.0',
  },
  {
    mainLanguages: 'English, Irish(Gaelic)',
    sayHello: 'English: Hello | Gaelic: Dia dhuit(singular)/Dia dhaoibh(plural)',
    countryCode: 'IE',
    countryName: 'Ireland',
    currencyCode: 'EUR',
    population: '4622917',
    fipsCode: 'EI',
    capital: 'Dublin',
    continentName: 'Europe',
    areaInSqKm: '70280.0',
  },
  {
    mainLanguages: 'Hebrew, Arabic',
    sayHello: 'Hebrew: Shalom/Halo | Arabic: Salam',
    countryCode: 'IL',
    countryName: 'Israel',
    currencyCode: 'ILS',
    population: '7353985',
    fipsCode: 'IS',
    capital: '',
    continentName: 'Asia',
    areaInSqKm: '20770.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'IM',
    countryName: 'Isle of Man',
    currencyCode: 'GBP',
    population: '75049',
    fipsCode: 'IM',
    capital: 'Douglas',
    continentName: 'Europe',
    areaInSqKm: '572.0',
  },
  {
    mainLanguages: 'English, Hindi',
    sayHello: 'English: Hello | Hindi: Namaste',
    countryCode: 'IN',
    countryName: 'India',
    currencyCode: 'INR',
    population: '1173108018',
    fipsCode: 'IN',
    capital: 'New Delhi',
    continentName: 'Asia',
    areaInSqKm: '3287590.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'IO',
    countryName: 'British Indian Ocean Territory',
    currencyCode: 'USD',
    population: '4000',
    fipsCode: 'IO',
    capital: '',
    continentName: 'Asia',
    areaInSqKm: '60.0',
  },
  {
    mainLanguages: 'Arabic, Kurdish',
    sayHello: 'Arabic: Salam | Kurdish: Merheba',
    countryCode: 'IQ',
    countryName: 'Iraq',
    currencyCode: 'IQD',
    population: '29671605',
    fipsCode: 'IZ',
    capital: 'Baghdad',
    continentName: 'Asia',
    areaInSqKm: '437072.0',
  },
  {
    mainLanguages: 'Persian',
    sayHello: 'Dorood/Salam',
    countryCode: 'IR',
    countryName: 'Iran',
    currencyCode: 'IRR',
    population: '76923300',
    fipsCode: 'IR',
    capital: 'Tehran',
    continentName: 'Asia',
    areaInSqKm: '1648000.0',
  },
  {
    mainLanguages: 'Icelandic',
    sayHello: 'Icelandic',
    countryCode: 'IS',
    countryName: 'Iceland',
    currencyCode: 'ISK',
    population: '308910',
    fipsCode: 'IC',
    capital: 'Reykjavik',
    continentName: 'Europe',
    areaInSqKm: '103000.0',
  },
  {
    mainLanguages: 'Italian',
    sayHello: 'Ciao',
    countryCode: 'IT',
    countryName: 'Italy',
    currencyCode: 'EUR',
    population: '60340328',
    fipsCode: 'IT',
    capital: 'Rome',
    continentName: 'Europe',
    areaInSqKm: '301230.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'JE',
    countryName: 'Jersey',
    currencyCode: 'GBP',
    population: '90812',
    fipsCode: 'JE',
    capital: 'Saint Helier',
    continentName: 'Europe',
    areaInSqKm: '116.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'JM',
    countryName: 'Jamaica',
    currencyCode: 'JMD',
    population: '2847232',
    fipsCode: 'JM',
    capital: 'Kingston',
    continentName: 'North America',
    areaInSqKm: '10991.0',
  },
  {
    mainLanguages: 'Arabic',
    sayHello: 'Salam',
    countryCode: 'JO',
    countryName: 'Jordan',
    currencyCode: 'JOD',
    population: '6407085',
    fipsCode: 'JO',
    capital: 'Amman',
    continentName: 'Asia',
    areaInSqKm: '92300.0',
  },
  {
    mainLanguages: 'Japanese',
    sayHello: 'Konnichiwa',
    countryCode: 'JP',
    countryName: 'Japan',
    currencyCode: 'JPY',
    population: '127288000',
    fipsCode: 'JA',
    capital: 'Tokyo',
    continentName: 'Asia',
    areaInSqKm: '377835.0',
  },
  {
    mainLanguages: 'English, Kiswahili',
    sayHello: 'English: Hello | Kiswahili: Hodi',
    countryCode: 'KE',
    countryName: 'Kenya',
    currencyCode: 'KES',
    population: '40046566',
    fipsCode: 'KE',
    capital: 'Nairobi',
    continentName: 'Africa',
    areaInSqKm: '582650.0',
  },
  {
    mainLanguages: 'Kyrgyz, Russian',
    sayHello: 'Kyrgyz: Kosh kelingiz | Russian:Privet',
    countryCode: 'KG',
    countryName: 'Kyrgyzstan',
    currencyCode: 'KGS',
    population: '5776500',
    fipsCode: 'KG',
    capital: 'Bishkek',
    continentName: 'Asia',
    areaInSqKm: '198500.0',
  },
  {
    mainLanguages: 'Khmer',
    sayHello: 'Surs dey',
    countryCode: 'KH',
    countryName: 'Cambodia',
    currencyCode: 'KHR',
    population: '14453680',
    fipsCode: 'CB',
    capital: 'Phnom Penh',
    continentName: 'Asia',
    areaInSqKm: '181040.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'KI',
    countryName: 'Kiribati',
    currencyCode: 'AUD',
    population: '92533',
    fipsCode: 'KR',
    capital: 'Tarawa',
    continentName: 'Oceania',
    areaInSqKm: '811.0',
  },
  {
    mainLanguages: 'Arabic, French',
    sayHello: 'Arabic: Salam | French: Salut',
    countryCode: 'KM',
    countryName: 'Comoros',
    currencyCode: 'KMF',
    population: '773407',
    fipsCode: 'CN',
    capital: 'Moroni',
    continentName: 'Africa',
    areaInSqKm: '2170.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'KN',
    countryName: 'Saint Kitts and Nevis',
    currencyCode: 'XCD',
    population: '51134',
    fipsCode: 'SC',
    capital: 'Basseterre',
    continentName: 'North America',
    areaInSqKm: '261.0',
  },
  {
    mainLanguages: 'Korean',
    sayHello: 'Annyeong',
    countryCode: 'KP',
    countryName: 'North Korea',
    currencyCode: 'KPW',
    population: '22912177',
    fipsCode: 'KN',
    capital: 'Pyongyang',
    continentName: 'Asia',
    areaInSqKm: '120540.0',
  },
  {
    mainLanguages: 'Korean',
    sayHello: 'Annyeong',
    countryCode: 'KR',
    countryName: 'South Korea',
    currencyCode: 'KRW',
    population: '48422644',
    fipsCode: 'KS',
    capital: 'Seoul',
    continentName: 'Asia',
    areaInSqKm: '98480.0',
  },
  {
    mainLanguages: 'Arabic',
    sayHello: 'Salam',
    countryCode: 'KW',
    countryName: 'Kuwait',
    currencyCode: 'KWD',
    population: '2789132',
    fipsCode: 'KU',
    capital: 'Kuwait City',
    continentName: 'Asia',
    areaInSqKm: '17820.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'KY',
    countryName: 'Cayman Islands',
    currencyCode: 'KYD',
    population: '44270',
    fipsCode: 'CJ',
    capital: 'George Town',
    continentName: 'North America',
    areaInSqKm: '262.0',
  },
  {
    mainLanguages: 'Kazakh, Russian',
    sayHello: 'Kazakh: Salem | Russian: Privet',
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
    currencyCode: 'KZT',
    population: '15340000',
    fipsCode: 'KZ',
    capital: 'Astana',
    continentName: 'Asia',
    areaInSqKm: '2717300.0',
  },
  {
    mainLanguages: '',
    sayHello: '',
    countryCode: 'LA',
    countryName: 'Laos',
    currencyCode: 'LAK',
    population: '6368162',
    fipsCode: 'LA',
    capital: 'Vientiane',
    continentName: 'Asia',
    areaInSqKm: '236800.0',
  },
  {
    mainLanguages: 'Lao, French',
    sayHello: 'Lao: Sába̖ai-di | French: Salut',
    countryCode: 'LB',
    countryName: 'Lebanon',
    currencyCode: 'LBP',
    population: '4125247',
    fipsCode: 'LE',
    capital: 'Beirut',
    continentName: 'Asia',
    areaInSqKm: '10400.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'LC',
    countryName: 'Saint Lucia',
    currencyCode: 'XCD',
    population: '160922',
    fipsCode: 'ST',
    capital: 'Castries',
    continentName: 'North America',
    areaInSqKm: '616.0',
  },
  {
    mainLanguages: 'German',
    sayHello: 'Hallo/Guten Tag',
    countryCode: 'LI',
    countryName: 'Liechtenstein',
    currencyCode: 'CHF',
    population: '35000',
    fipsCode: 'LS',
    capital: 'Vaduz',
    continentName: 'Europe',
    areaInSqKm: '160.0',
  },
  {
    mainLanguages: 'Sinhalese, Tamil',
    sayHello: 'Sinhalese: Āyubōvan | Tamil: Vaṇakkam',
    countryCode: 'LK',
    countryName: 'Sri Lanka',
    currencyCode: 'LKR',
    population: '21513990',
    fipsCode: 'CE',
    capital: 'Colombo',
    continentName: 'Asia',
    areaInSqKm: '65610.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'LR',
    countryName: 'Liberia',
    currencyCode: 'LRD',
    population: '3685076',
    fipsCode: 'LI',
    capital: 'Monrovia',
    continentName: 'Africa',
    areaInSqKm: '111370.0',
  },
  {
    mainLanguages: 'Sesotho, English',
    sayHello: 'Sesotho: Lumela | English: Hello',
    countryCode: 'LS',
    countryName: 'Lesotho',
    currencyCode: 'LSL',
    population: '1919552',
    fipsCode: 'LT',
    capital: 'Maseru',
    continentName: 'Africa',
    areaInSqKm: '30355.0',
  },
  {
    mainLanguages: 'Lithuanian',
    sayHello: 'Labas',
    countryCode: 'LT',
    countryName: 'Lithuania',
    currencyCode: 'EUR',
    population: '2944459',
    fipsCode: 'LH',
    capital: 'Vilnius',
    continentName: 'Europe',
    areaInSqKm: '65200.0',
  },
  {
    mainLanguages: 'Luxembourgish, German, French',
    sayHello: 'Luxembourgish: Moien/Salut | German: Hallo | French: Salut',
    countryCode: 'LU',
    countryName: 'Luxembourg',
    currencyCode: 'EUR',
    population: '497538',
    fipsCode: 'LU',
    capital: 'Luxembourg',
    continentName: 'Europe',
    areaInSqKm: '2586.0',
  },
  {
    mainLanguages: 'Latvian',
    sayHello: 'Sveiki',
    countryCode: 'LV',
    countryName: 'Latvia',
    currencyCode: 'EUR',
    population: '2217969',
    fipsCode: 'LG',
    capital: 'Riga',
    continentName: 'Europe',
    areaInSqKm: '64589.0',
  },
  {
    mainLanguages: 'Arabic',
    sayHello: 'Salam',
    countryCode: 'LY',
    countryName: 'Libya',
    currencyCode: 'LYD',
    population: '6461454',
    fipsCode: 'LY',
    capital: 'Tripoli',
    continentName: 'Africa',
    areaInSqKm: '1759540.0',
  },
  {
    mainLanguages: 'Arabic, French',
    sayHello: 'Arabic: Salam | French: Salut',
    countryCode: 'MA',
    countryName: 'Morocco',
    currencyCode: 'MAD',
    population: '31627428',
    fipsCode: 'MO',
    capital: 'Rabat',
    continentName: 'Africa',
    areaInSqKm: '446550.0',
  },
  {
    mainLanguages: 'French',
    sayHello: 'Salut',
    countryCode: 'MC',
    countryName: 'Monaco',
    currencyCode: 'EUR',
    population: '32965',
    fipsCode: 'MN',
    capital: 'Monaco',
    continentName: 'Europe',
    areaInSqKm: '1.95',
  },
  {
    mainLanguages: 'Romanian, Russian',
    sayHello: 'Romanian: Salut | Russian: Privet',
    countryCode: 'MD',
    countryName: 'Moldova',
    currencyCode: 'MDL',
    population: '4324000',
    fipsCode: 'MD',
    capital: 'Chişinău',
    continentName: 'Europe',
    areaInSqKm: '33843.0',
  },
  {
    mainLanguages: 'Montenegrin',
    sayHello: 'Halo',
    countryCode: 'ME',
    countryName: 'Montenegro',
    currencyCode: 'EUR',
    population: '666730',
    fipsCode: 'MJ',
    capital: 'Podgorica',
    continentName: 'Europe',
    areaInSqKm: '14026.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'MF',
    countryName: 'Saint Martin',
    currencyCode: 'EUR',
    population: '35925',
    fipsCode: 'RN',
    capital: 'Marigot',
    continentName: 'North America',
    areaInSqKm: '53.0',
  },
  {
    mainLanguages: 'Malagasy, French',
    sayHello: 'Malagasy: Salama | French: Salut',
    countryCode: 'MG',
    countryName: 'Madagascar',
    currencyCode: 'MGA',
    population: '21281844',
    fipsCode: 'MA',
    capital: 'Antananarivo',
    continentName: 'Africa',
    areaInSqKm: '587040.0',
  },
  {
    mainLanguages: 'Marshallese, English',
    sayHello: 'Marshallese: Yokwe | English: Hello',
    countryCode: 'MH',
    countryName: 'Marshall Islands',
    currencyCode: 'USD',
    population: '65859',
    fipsCode: 'RM',
    capital: 'Majuro',
    continentName: 'Oceania',
    areaInSqKm: '181.3',
  },
  {
    mainLanguages: 'Macedonian',
    sayHello: 'Zdravo',
    countryCode: 'MK',
    countryName: 'Macedonia',
    currencyCode: 'MKD',
    population: '2062294',
    fipsCode: 'MK',
    capital: 'Skopje',
    continentName: 'Europe',
    areaInSqKm: '25333.0',
  },
  {
    mainLanguages: 'French',
    sayHello: 'Salut',
    countryCode: 'ML',
    countryName: 'Mali',
    currencyCode: 'XOF',
    population: '13796354',
    fipsCode: 'ML',
    capital: 'Bamako',
    continentName: 'Africa',
    areaInSqKm: '1240000.0',
  },
  {
    mainLanguages: 'Burmese',
    sayHello: 'Maingalarpar',
    countryCode: 'MM',
    countryName: 'Myanmar [Burma]',
    currencyCode: 'MMK',
    population: '53414374',
    fipsCode: 'BM',
    capital: 'Naypyitaw',
    continentName: 'Asia',
    areaInSqKm: '678500.0',
  },
  {
    mainLanguages: '',
    sayHello: '',
    countryCode: 'MN',
    countryName: 'Mongolia',
    currencyCode: 'MNT',
    population: '3086918',
    fipsCode: 'MG',
    capital: 'Ulan Bator',
    continentName: 'Asia',
    areaInSqKm: '1565000.0',
  },
  {
    mainLanguages: 'Mongolian',
    sayHello: 'Sain uu?',
    countryCode: 'MO',
    countryName: 'Macao',
    currencyCode: 'MOP',
    population: '449198',
    fipsCode: 'MC',
    capital: 'Macao',
    continentName: 'Asia',
    areaInSqKm: '254.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'MP',
    countryName: 'Northern Mariana Islands',
    currencyCode: 'USD',
    population: '53883',
    fipsCode: 'CQ',
    capital: 'Saipan',
    continentName: 'Oceania',
    areaInSqKm: '477.0',
  },
  {
    mainLanguages: 'French',
    sayHello: 'Salut',
    countryCode: 'MQ',
    countryName: 'Martinique',
    currencyCode: 'EUR',
    population: '432900',
    fipsCode: 'MB',
    capital: 'Fort-de-France',
    continentName: 'North America',
    areaInSqKm: '1100.0',
  },
  {
    mainLanguages: 'Arabic',
    sayHello: 'Salam',
    countryCode: 'MR',
    countryName: 'Mauritania',
    currencyCode: 'MRO',
    population: '3205060',
    fipsCode: 'MR',
    capital: 'Nouakchott',
    continentName: 'Africa',
    areaInSqKm: '1030700.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'MS',
    countryName: 'Montserrat',
    currencyCode: 'XCD',
    population: '9341',
    fipsCode: 'MH',
    capital: 'Plymouth',
    continentName: 'North America',
    areaInSqKm: '102.0',
  },
  {
    mainLanguages: 'Maltese, English',
    sayHello: 'Maltese:Ħello/Hawn | English:Hello',
    countryCode: 'MT',
    countryName: 'Malta',
    currencyCode: 'EUR',
    population: '403000',
    fipsCode: 'MT',
    capital: 'Valletta',
    continentName: 'Europe',
    areaInSqKm: '316.0',
  },
  {
    mainLanguages: 'English, French',
    sayHello: 'English: Hello | French: Bonjour',
    countryCode: 'MU',
    countryName: 'Mauritius',
    currencyCode: 'MUR',
    population: '1294104',
    fipsCode: 'MP',
    capital: 'Port Louis',
    continentName: 'Africa',
    areaInSqKm: '2040.0',
  },
  {
    mainLanguages: 'Maldivian',
    sayHello: 'Kihineh?',
    countryCode: 'MV',
    countryName: 'Maldives',
    currencyCode: 'MVR',
    population: '395650',
    fipsCode: 'MV',
    capital: 'Malé',
    continentName: 'Asia',
    areaInSqKm: '300.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'MW',
    countryName: 'Malawi',
    currencyCode: 'MWK',
    population: '15447500',
    fipsCode: 'MI',
    capital: 'Lilongwe',
    continentName: 'Africa',
    areaInSqKm: '118480.0',
  },
  {
    mainLanguages: 'Spanish',
    sayHello: 'Hola',
    countryCode: 'MX',
    countryName: 'Mexico',
    currencyCode: 'MXN',
    population: '112468855',
    fipsCode: 'MX',
    capital: 'Mexico City',
    continentName: 'North America',
    areaInSqKm: '1972550.0',
  },
  {
    mainLanguages: 'Malay',
    sayHello: 'Selamat petang',
    countryCode: 'MY',
    countryName: 'Malaysia',
    currencyCode: 'MYR',
    population: '28274729',
    fipsCode: 'MY',
    capital: 'Kuala Lumpur',
    continentName: 'Asia',
    areaInSqKm: '329750.0',
  },
  {
    mainLanguages: 'Portugese',
    sayHello: 'Olá',
    countryCode: 'MZ',
    countryName: 'Mozambique',
    currencyCode: 'MZN',
    population: '22061451',
    fipsCode: 'MZ',
    capital: 'Maputo',
    continentName: 'Africa',
    areaInSqKm: '801590.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'NA',
    countryName: 'Namibia',
    currencyCode: 'NAD',
    population: '2128471',
    fipsCode: 'WA',
    capital: 'Windhoek',
    continentName: 'Africa',
    areaInSqKm: '825418.0',
  },
  {
    mainLanguages: 'French',
    sayHello: 'Salut',
    countryCode: 'NC',
    countryName: 'New Caledonia',
    currencyCode: 'XPF',
    population: '216494',
    fipsCode: 'NC',
    capital: 'Noumea',
    continentName: 'Oceania',
    areaInSqKm: '19060.0',
  },
  {
    mainLanguages: 'French, Hausa, Fulfulde',
    sayHello: 'French: Salut | Hausa: Sannu , Fulfulde: Sannu',
    countryCode: 'NE',
    countryName: 'Niger',
    currencyCode: 'XOF',
    population: '15878271',
    fipsCode: 'NG',
    capital: 'Niamey',
    continentName: 'Africa',
    areaInSqKm: '1267000.0',
  },
  {
    mainLanguages: 'English, Norfuk',
    sayHello: 'English: Hello | Norfuk: Watawieh',
    countryCode: 'NF',
    countryName: 'Norfolk Island',
    currencyCode: 'AUD',
    population: '1828',
    fipsCode: 'NF',
    capital: 'Kingston',
    continentName: 'Oceania',
    areaInSqKm: '34.6',
  },
  {
    mainLanguages: 'English, Hausa, Igbo, Yoruba',
    sayHello: 'English: Hello | Hausa: Sannu | Igbo: Nnọọ | Yoruba: Ẹ n lẹ',
    countryCode: 'NG',
    countryName: 'Nigeria',
    currencyCode: 'NGN',
    population: '154000000',
    fipsCode: 'NI',
    capital: 'Abuja',
    continentName: 'Africa',
    areaInSqKm: '923768.0',
  },
  {
    mainLanguages: 'Spanish, English',
    sayHello: 'Spanish: Hola | English: Hello',
    countryCode: 'NI',
    countryName: 'Nicaragua',
    currencyCode: 'NIO',
    population: '5995928',
    fipsCode: 'NU',
    capital: 'Managua',
    continentName: 'North America',
    areaInSqKm: '129494.0',
  },
  {
    mainLanguages: 'Dutch',
    sayHello: 'Goeiedag',
    countryCode: 'NL',
    countryName: 'Netherlands',
    currencyCode: 'EUR',
    population: '16645000',
    fipsCode: 'NL',
    capital: 'Amsterdam',
    continentName: 'Europe',
    areaInSqKm: '41526.0',
  },
  {
    mainLanguages: 'Norweigian',
    sayHello: 'Goddag',
    countryCode: 'NO',
    countryName: 'Norway',
    currencyCode: 'NOK',
    population: '5009150',
    fipsCode: 'NO',
    capital: 'Oslo',
    continentName: 'Europe',
    areaInSqKm: '324220.0',
  },
  {
    mainLanguages: 'Nepali',
    sayHello: 'Namaste',
    countryCode: 'NP',
    countryName: 'Nepal',
    currencyCode: 'NPR',
    population: '28951852',
    fipsCode: 'NP',
    capital: 'Kathmandu',
    continentName: 'Asia',
    areaInSqKm: '140800.0',
  },
  {
    mainLanguages: '',
    sayHello: '',
    countryCode: 'NR',
    countryName: 'Nauru',
    currencyCode: 'AUD',
    population: '10065',
    fipsCode: 'NR',
    capital: 'Yaren',
    continentName: 'Oceania',
    areaInSqKm: '21.0',
  },
  {
    mainLanguages: 'English, Nauruan',
    sayHello: 'English: Hello | Nauruan: Ekamowir Omo ',
    countryCode: 'NU',
    countryName: 'Niue',
    currencyCode: 'NZD',
    population: '2166',
    fipsCode: 'NE',
    capital: 'Alofi',
    continentName: 'Oceania',
    areaInSqKm: '260.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'NZ',
    countryName: 'New Zealand',
    currencyCode: 'NZD',
    population: '4252277',
    fipsCode: 'NZ',
    capital: 'Wellington',
    continentName: 'Oceania',
    areaInSqKm: '268680.0',
  },
  {
    mainLanguages: 'Arabic',
    sayHello: 'Salam',
    countryCode: 'OM',
    countryName: 'Oman',
    currencyCode: 'OMR',
    population: '2967717',
    fipsCode: 'MU',
    capital: 'Muscat',
    continentName: 'Asia',
    areaInSqKm: '212460.0',
  },
  {
    mainLanguages: 'Spanish',
    sayHello: 'Hola',
    countryCode: 'PA',
    countryName: 'Panama',
    currencyCode: 'PAB',
    population: '3410676',
    fipsCode: 'PM',
    capital: 'Panama City',
    continentName: 'North America',
    areaInSqKm: '78200.0',
  },
  {
    mainLanguages: 'Spanish',
    sayHello: 'Hola',
    countryCode: 'PE',
    countryName: 'Peru',
    currencyCode: 'PEN',
    population: '29907003',
    fipsCode: 'PE',
    capital: 'Lima',
    continentName: 'South America',
    areaInSqKm: '1285220.0',
  },
  {
    mainLanguages: 'French',
    sayHello: 'Salut',
    countryCode: 'PF',
    countryName: 'French Polynesia',
    currencyCode: 'XPF',
    population: '270485',
    fipsCode: 'FP',
    capital: 'Papeete',
    continentName: 'Oceania',
    areaInSqKm: '4167.0',
  },
  {
    mainLanguages: 'Hiri Motu',
    sayHello: 'Dina namon',
    countryCode: 'PG',
    countryName: 'Papua New Guinea',
    currencyCode: 'PGK',
    population: '6064515',
    fipsCode: 'PP',
    capital: 'Port Moresby',
    continentName: 'Oceania',
    areaInSqKm: '462840.0',
  },
  {
    mainLanguages: 'English, Filipino',
    sayHello: 'English: Hello | Filipino: Kamusta',
    countryCode: 'PH',
    countryName: 'Philippines',
    currencyCode: 'PHP',
    population: '99900177',
    fipsCode: 'RP',
    capital: 'Manila',
    continentName: 'Asia',
    areaInSqKm: '300000.0',
  },
  {
    mainLanguages: 'English, Urdu',
    sayHello: 'English: Hello | Urdu: Salam',
    countryCode: 'PK',
    countryName: 'Pakistan',
    currencyCode: 'PKR',
    population: '184404791',
    fipsCode: 'PK',
    capital: 'Islamabad',
    continentName: 'Asia',
    areaInSqKm: '803940.0',
  },
  {
    mainLanguages: 'Polish',
    sayHello: 'Cześć',
    countryCode: 'PL',
    countryName: 'Poland',
    currencyCode: 'PLN',
    population: '38500000',
    fipsCode: 'PL',
    capital: 'Warsaw',
    continentName: 'Europe',
    areaInSqKm: '312685.0',
  },
  {
    mainLanguages: 'French',
    sayHello: 'Salut',
    countryCode: 'PM',
    countryName: 'Saint Pierre and Miquelon',
    currencyCode: 'EUR',
    population: '7012',
    fipsCode: 'SB',
    capital: 'Saint-Pierre',
    continentName: 'North America',
    areaInSqKm: '242.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'PN',
    countryName: 'Pitcairn Islands',
    currencyCode: 'NZD',
    population: '46',
    fipsCode: 'PC',
    capital: 'Adamstown',
    continentName: 'Oceania',
    areaInSqKm: '47.0',
  },
  {
    mainLanguages: 'Spanish, English',
    sayHello: 'Spanish: Hola | English: Hello',
    countryCode: 'PR',
    countryName: 'Puerto Rico',
    currencyCode: 'USD',
    population: '3916632',
    fipsCode: 'RQ',
    capital: 'San Juan',
    continentName: 'North America',
    areaInSqKm: '9104.0',
  },
  {
    mainLanguages: 'Arabic',
    sayHello: 'Salam',
    countryCode: 'PS',
    countryName: 'Palestine',
    currencyCode: 'ILS',
    population: '3800000',
    fipsCode: 'WE',
    capital: '',
    continentName: 'Asia',
    areaInSqKm: '5970.0',
  },
  {
    mainLanguages: 'Portuguese',
    sayHello: 'Olá',
    countryCode: 'PT',
    countryName: 'Portugal',
    currencyCode: 'EUR',
    population: '10676000',
    fipsCode: 'PO',
    capital: 'Lisbon',
    continentName: 'Europe',
    areaInSqKm: '92391.0',
  },
  {
    mainLanguages: 'Palauan, English',
    sayHello: 'Palauan: Alii | English: Hello',
    countryCode: 'PW',
    countryName: 'Palau',
    currencyCode: 'USD',
    population: '19907',
    fipsCode: 'PS',
    capital: 'Melekeok',
    continentName: 'Oceania',
    areaInSqKm: '458.0',
  },
  {
    mainLanguages: 'Spanish, Guaraní',
    sayHello: 'Spanish: Hola | Guaraní: Mbaé’chepa',
    countryCode: 'PY',
    countryName: 'Paraguay',
    currencyCode: 'PYG',
    population: '6375830',
    fipsCode: 'PA',
    capital: 'Asunción',
    continentName: 'South America',
    areaInSqKm: '406750.0',
  },
  {
    mainLanguages: 'Arabic',
    sayHello: 'Salam',
    countryCode: 'QA',
    countryName: 'Qatar',
    currencyCode: 'QAR',
    population: '840926',
    fipsCode: 'QA',
    capital: 'Doha',
    continentName: 'Asia',
    areaInSqKm: '11437.0',
  },
  {
    mainLanguages: 'French',
    sayHello: 'Salut',
    countryCode: 'RE',
    countryName: 'Réunion',
    currencyCode: 'EUR',
    population: '776948',
    fipsCode: 'RE',
    capital: 'Saint-Denis',
    continentName: 'Africa',
    areaInSqKm: '2517.0',
  },
  {
    mainLanguages: 'Romanian',
    sayHello: 'Salut',
    countryCode: 'RO',
    countryName: 'Romania',
    currencyCode: 'RON',
    population: '21959278',
    fipsCode: 'RO',
    capital: 'Bucharest',
    continentName: 'Europe',
    areaInSqKm: '237500.0',
  },
  {
    mainLanguages: 'Serbian',
    sayHello: 'Zdravo',
    countryCode: 'RS',
    countryName: 'Serbia',
    currencyCode: 'RSD',
    population: '7344847',
    fipsCode: 'RI',
    capital: 'Belgrade',
    continentName: 'Europe',
    areaInSqKm: '88361.0',
  },
  {
    mainLanguages: 'Russian',
    sayHello: 'Privet',
    countryCode: 'RU',
    countryName: 'Russia',
    currencyCode: 'RUB',
    population: '140702000',
    fipsCode: 'RS',
    capital: 'Moscow',
    continentName: 'Europe',
    areaInSqKm: '1.71E7',
  },
  {
    mainLanguages: 'Kinyarwanda, French, English',
    sayHello: 'Kinyarwanda: Muraho/Bite (inf)  | French: Salut | English: Hello',
    countryCode: 'RW',
    countryName: 'Rwanda',
    currencyCode: 'RWF',
    population: '11055976',
    fipsCode: 'RW',
    capital: 'Kigali',
    continentName: 'Africa',
    areaInSqKm: '26338.0',
  },
  {
    mainLanguages: 'Arabic',
    sayHello: 'Salam',
    countryCode: 'SA',
    countryName: 'Saudi Arabia',
    currencyCode: 'SAR',
    population: '25731776',
    fipsCode: 'SA',
    capital: 'Riyadh',
    continentName: 'Asia',
    areaInSqKm: '1960582.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'SB',
    countryName: 'Solomon Islands',
    currencyCode: 'SBD',
    population: '559198',
    fipsCode: 'BP',
    capital: 'Honiara',
    continentName: 'Oceania',
    areaInSqKm: '28450.0',
  },
  {
    mainLanguages: 'English, French',
    sayHello: 'English: Hello | French: Salut',
    countryCode: 'SC',
    countryName: 'Seychelles',
    currencyCode: 'SCR',
    population: '88340',
    fipsCode: 'SE',
    capital: 'Victoria',
    continentName: 'Africa',
    areaInSqKm: '455.0',
  },
  {
    mainLanguages: 'Arabic, English',
    sayHello: 'Arabic: Salam | English: Hello',
    countryCode: 'SD',
    countryName: 'Sudan',
    currencyCode: 'SDG',
    population: '35000000',
    fipsCode: 'SU',
    capital: 'Khartoum',
    continentName: 'Africa',
    areaInSqKm: '1861484.0',
  },
  {
    mainLanguages: 'Swedish',
    sayHello: 'God dag(formal), Hej(informal)',
    countryCode: 'SE',
    countryName: 'Sweden',
    currencyCode: 'SEK',
    population: '9828655',
    fipsCode: 'SW',
    capital: 'Stockholm',
    continentName: 'Europe',
    areaInSqKm: '449964.0',
  },
  {
    mainLanguages: 'English, Malay, Mandarin, Tamil',
    sayHello: 'English: Hello | Malay: Namaste | Mandarin: Nǐ hǎo | Tamil: Vaṇakkã',
    countryCode: 'SG',
    countryName: 'Singapore',
    currencyCode: 'SGD',
    population: '4701069',
    fipsCode: 'SN',
    capital: 'Singapore',
    continentName: 'Asia',
    areaInSqKm: '692.7',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'SH',
    countryName: 'Saint Helena',
    currencyCode: 'SHP',
    population: '7460',
    fipsCode: 'SH',
    capital: 'Jamestown',
    continentName: 'Africa',
    areaInSqKm: '410.0',
  },
  {
    mainLanguages: 'Slovene',
    sayHello: 'Zdravo',
    countryCode: 'SI',
    countryName: 'Slovenia',
    currencyCode: 'EUR',
    population: '2007000',
    fipsCode: 'SI',
    capital: 'Ljubljana',
    continentName: 'Europe',
    areaInSqKm: '20273.0',
  },
  {
    mainLanguages: 'Penguinese',
    sayHello: 'Squak! Squak!',
    countryCode: 'SJ',
    countryName: 'Svalbard and Jan Mayen',
    currencyCode: 'NOK',
    population: '2550',
    fipsCode: 'SV',
    capital: 'Longyearbyen',
    continentName: 'Europe',
    areaInSqKm: '62049.0',
  },
  {
    mainLanguages: 'Slovak',
    sayHello: 'Ahoj',
    countryCode: 'SK',
    countryName: 'Slovakia',
    currencyCode: 'EUR',
    population: '5455000',
    fipsCode: 'LO',
    capital: 'Bratislava',
    continentName: 'Europe',
    areaInSqKm: '48845.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'SL',
    countryName: 'Sierra Leone',
    currencyCode: 'SLL',
    population: '5245695',
    fipsCode: 'SL',
    capital: 'Freetown',
    continentName: 'Africa',
    areaInSqKm: '71740.0',
  },
  {
    mainLanguages: 'Italian',
    sayHello: 'Ciao',
    countryCode: 'SM',
    countryName: 'San Marino',
    currencyCode: 'EUR',
    population: '31477',
    fipsCode: 'SM',
    capital: 'San Marino',
    continentName: 'Europe',
    areaInSqKm: '61.2',
  },
  {
    mainLanguages: 'French',
    sayHello: 'Salut',
    countryCode: 'SN',
    countryName: 'Senegal',
    currencyCode: 'XOF',
    population: '12323252',
    fipsCode: 'SG',
    capital: 'Dakar',
    continentName: 'Africa',
    areaInSqKm: '196190.0',
  },
  {
    mainLanguages: 'Somali, Arabic',
    sayHello: 'Somali: Is ka warran | Arabic: Salam',
    countryCode: 'SO',
    countryName: 'Somalia',
    currencyCode: 'SOS',
    population: '10112453',
    fipsCode: 'SO',
    capital: 'Mogadishu',
    continentName: 'Africa',
    areaInSqKm: '637657.0',
  },
  {
    mainLanguages: 'Dutch',
    sayHello: 'Goeiedag',
    countryCode: 'SR',
    countryName: 'Suriname',
    currencyCode: 'SRD',
    population: '492829',
    fipsCode: 'NS',
    capital: 'Paramaribo',
    continentName: 'South America',
    areaInSqKm: '163270.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'SS',
    countryName: 'South Sudan',
    currencyCode: 'SSP',
    population: '8260490',
    fipsCode: 'OD',
    capital: 'Juba',
    continentName: 'Africa',
    areaInSqKm: '644329.0',
  },
  {
    mainLanguages: 'Portugese',
    sayHello: 'Ola',
    countryCode: 'ST',
    countryName: 'São Tomé and Príncipe',
    currencyCode: 'STD',
    population: '175808',
    fipsCode: 'TP',
    capital: 'São Tomé',
    continentName: 'Africa',
    areaInSqKm: '1001.0',
  },
  {
    mainLanguages: 'Spanish',
    sayHello: 'Hola',
    countryCode: 'SV',
    countryName: 'El Salvador',
    currencyCode: 'USD',
    population: '6052064',
    fipsCode: 'ES',
    capital: 'San Salvador',
    continentName: 'North America',
    areaInSqKm: '21040.0',
  },
  {
    mainLanguages: 'Dutch, English',
    sayHello: 'Dutch: Goeiedag | English: Hello',
    countryCode: 'SX',
    countryName: 'Sint Maarten',
    currencyCode: 'ANG',
    population: '37429',
    fipsCode: 'NN',
    capital: 'Philipsburg',
    continentName: 'North America',
    areaInSqKm: '21.0',
  },
  {
    mainLanguages: 'Arabic',
    sayHello: 'Salam',
    countryCode: 'SY',
    countryName: 'Syria',
    currencyCode: 'SYP',
    population: '22198110',
    fipsCode: 'SY',
    capital: 'Damascus',
    continentName: 'Asia',
    areaInSqKm: '185180.0',
  },
  {
    mainLanguages: 'Swazi',
    sayHello: 'Sawubona',
    countryCode: 'SZ',
    countryName: 'Swaziland',
    currencyCode: 'SZL',
    population: '1354051',
    fipsCode: 'WZ',
    capital: 'Mbabane',
    continentName: 'Africa',
    areaInSqKm: '17363.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'TC',
    countryName: 'Turks and Caicos Islands',
    currencyCode: 'USD',
    population: '20556',
    fipsCode: 'TK',
    capital: 'Cockburn Town',
    continentName: 'North America',
    areaInSqKm: '430.0',
  },
  {
    mainLanguages: 'Arabic, French',
    sayHello: 'Arabic: Salam | French: Salut',
    countryCode: 'TD',
    countryName: 'Chad',
    currencyCode: 'XAF',
    population: '10543464',
    fipsCode: 'CD',
    capital: "N'Djamena",
    continentName: 'Africa',
    areaInSqKm: '1284000.0',
  },
  {
    mainLanguages: 'French',
    sayHello: 'Salut',
    countryCode: 'TF',
    countryName: 'French Southern Territories',
    currencyCode: 'EUR',
    population: '140',
    fipsCode: 'FS',
    capital: 'Port-aux-Français',
    continentName: 'Antarctica',
    areaInSqKm: '7829.0',
  },
  {
    mainLanguages: 'French',
    sayHello: 'Salut',
    countryCode: 'TG',
    countryName: 'Togo',
    currencyCode: 'XOF',
    population: '6587239',
    fipsCode: 'TO',
    capital: 'Lomé',
    continentName: 'Africa',
    areaInSqKm: '56785.0',
  },
  {
    mainLanguages: 'Thai',
    sayHello: 'Swạsdī',
    countryCode: 'TH',
    countryName: 'Thailand',
    currencyCode: 'THB',
    population: '67089500',
    fipsCode: 'TH',
    capital: 'Bangkok',
    continentName: 'Asia',
    areaInSqKm: '514000.0',
  },
  {
    mainLanguages: 'Persian, Russian',
    sayHello: 'Persian: Salam | Russian: Privet',
    countryCode: 'TJ',
    countryName: 'Tajikistan',
    currencyCode: 'TJS',
    population: '7487489',
    fipsCode: 'TI',
    capital: 'Dushanbe',
    continentName: 'Asia',
    areaInSqKm: '143100.0',
  },
  {
    mainLanguages: 'Tokelauan, English',
    sayHello: ' Tokelauan: Mâlô nî | English: Hello',
    countryCode: 'TK',
    countryName: 'Tokelau',
    currencyCode: 'NZD',
    population: '1466',
    fipsCode: 'TL',
    capital: '',
    continentName: 'Oceania',
    areaInSqKm: '10.0',
  },
  {
    mainLanguages: 'Tetum, Portugese',
    sayHello: 'Tetum: Elo/Hi | Portugese: Ola',
    countryCode: 'TL',
    countryName: 'East Timor',
    currencyCode: 'USD',
    population: '1154625',
    fipsCode: 'TT',
    capital: 'Dili',
    continentName: 'Oceania',
    areaInSqKm: '15007.0',
  },
  {
    mainLanguages: 'Turkmen',
    sayHello: 'Salam',
    countryCode: 'TM',
    countryName: 'Turkmenistan',
    currencyCode: 'TMT',
    population: '4940916',
    fipsCode: 'TX',
    capital: 'Ashgabat',
    continentName: 'Asia',
    areaInSqKm: '488100.0',
  },
  {
    mainLanguages: 'Arabic',
    sayHello: 'Salam',
    countryCode: 'TN',
    countryName: 'Tunisia',
    currencyCode: 'TND',
    population: '10589025',
    fipsCode: 'TS',
    capital: 'Tunis',
    continentName: 'Africa',
    areaInSqKm: '163610.0',
  },
  {
    mainLanguages: 'Tongan, English',
    sayHello: 'Tongan: Mâlô e lelei | English: Hello',
    countryCode: 'TO',
    countryName: 'Tonga',
    currencyCode: 'TOP',
    population: '122580',
    fipsCode: 'TN',
    capital: "Nuku'alofa",
    continentName: 'Oceania',
    areaInSqKm: '748.0',
  },
  {
    mainLanguages: 'Turkish',
    sayHello: 'Merhaba/Salam',
    countryCode: 'TR',
    countryName: 'Turkey',
    currencyCode: 'TRY',
    population: '77804122',
    fipsCode: 'TU',
    capital: 'Ankara',
    continentName: 'Asia',
    areaInSqKm: '780580.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'TT',
    countryName: 'Trinidad and Tobago',
    currencyCode: 'TTD',
    population: '1228691',
    fipsCode: 'TD',
    capital: 'Port of Spain',
    continentName: 'North America',
    areaInSqKm: '5128.0',
  },
  {
    mainLanguages: 'Tuvaluan, English',
    sayHello: 'Tuvaluan: Tālofa | English: Hello',
    countryCode: 'TV',
    countryName: 'Tuvalu',
    currencyCode: 'AUD',
    population: '10472',
    fipsCode: 'TV',
    capital: 'Funafuti',
    continentName: 'Oceania',
    areaInSqKm: '26.0',
  },
  {
    mainLanguages: 'Mandarin, Tiawanese',
    sayHello: 'Mandarin: Nǐ hǎo | Taiwanese: Lí-hó',
    countryCode: 'TW',
    countryName: 'Taiwan',
    currencyCode: 'TWD',
    population: '22894384',
    fipsCode: 'TW',
    capital: 'Taipei',
    continentName: 'Asia',
    areaInSqKm: '35980.0',
  },
  {
    mainLanguages: 'Swahili, English',
    sayHello: 'Swahili: Hodi | English: Hello',
    countryCode: 'TZ',
    countryName: 'Tanzania',
    currencyCode: 'TZS',
    population: '41892895',
    fipsCode: 'TZ',
    capital: 'Dodoma',
    continentName: 'Africa',
    areaInSqKm: '945087.0',
  },
  {
    mainLanguages: 'Ukranian',
    sayHello: 'Privet',
    countryCode: 'UA',
    countryName: 'Ukraine',
    currencyCode: 'UAH',
    population: '45415596',
    fipsCode: 'UP',
    capital: 'Kiev',
    continentName: 'Europe',
    areaInSqKm: '603700.0',
  },
  {
    mainLanguages: 'Swahili, English',
    sayHello: 'Swahili: Hodi | English: Hello',
    countryCode: 'UG',
    countryName: 'Uganda',
    currencyCode: 'UGX',
    population: '33398682',
    fipsCode: 'UG',
    capital: 'Kampala',
    continentName: 'Africa',
    areaInSqKm: '236040.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'UM',
    countryName: 'U.S. Minor Outlying Islands',
    currencyCode: 'USD',
    population: '0',
    fipsCode: '',
    capital: '',
    continentName: 'Oceania',
    areaInSqKm: '0.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'US',
    countryName: 'United States',
    currencyCode: 'USD',
    population: '310232863',
    fipsCode: 'US',
    capital: 'Washington',
    continentName: 'North America',
    areaInSqKm: '9629091.0',
  },
  {
    mainLanguages: 'Spanish',
    sayHello: 'Hola',
    countryCode: 'UY',
    countryName: 'Uruguay',
    currencyCode: 'UYU',
    population: '3477000',
    fipsCode: 'UY',
    capital: 'Montevideo',
    continentName: 'South America',
    areaInSqKm: '176220.0',
  },
  {
    mainLanguages: 'Uzbek',
    sayHello: 'Salom',
    countryCode: 'UZ',
    countryName: 'Uzbekistan',
    currencyCode: 'UZS',
    population: '27865738',
    fipsCode: 'UZ',
    capital: 'Tashkent',
    continentName: 'Asia',
    areaInSqKm: '447400.0',
  },
  {
    mainLanguages: 'Italian',
    sayHello: 'Ciao',
    countryCode: 'VA',
    countryName: 'Vatican City',
    currencyCode: 'EUR',
    population: '921',
    fipsCode: 'VT',
    capital: 'Vatican City',
    continentName: 'Europe',
    areaInSqKm: '0.44',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'VC',
    countryName: 'Saint Vincent and the Grenadines',
    currencyCode: 'XCD',
    population: '104217',
    fipsCode: 'VC',
    capital: 'Kingstown',
    continentName: 'North America',
    areaInSqKm: '389.0',
  },
  {
    mainLanguages: 'Spanish',
    sayHello: 'Hola',
    countryCode: 'VE',
    countryName: 'Venezuela',
    currencyCode: 'VEF',
    population: '27223228',
    fipsCode: 'VE',
    capital: 'Caracas',
    continentName: 'South America',
    areaInSqKm: '912050.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'VG',
    countryName: 'British Virgin Islands',
    currencyCode: 'USD',
    population: '21730',
    fipsCode: 'VI',
    capital: 'Road Town',
    continentName: 'North America',
    areaInSqKm: '153.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'VI',
    countryName: 'U.S. Virgin Islands',
    currencyCode: 'USD',
    population: '108708',
    fipsCode: 'VQ',
    capital: 'Charlotte Amalie',
    continentName: 'North America',
    areaInSqKm: '352.0',
  },
  {
    mainLanguages: 'Vietnamese',
    sayHello: 'Chào anh(male)/Chào chị(female)',
    countryCode: 'VN',
    countryName: 'Vietnam',
    currencyCode: 'VND',
    population: '89571130',
    fipsCode: 'VM',
    capital: 'Hanoi',
    continentName: 'Asia',
    areaInSqKm: '329560.0',
  },
  {
    mainLanguages: 'Bislama, French, English',
    sayHello: 'Bislama: Halo |  French: Salut | English: Hello',
    countryCode: 'VU',
    countryName: 'Vanuatu',
    currencyCode: 'VUV',
    population: '221552',
    fipsCode: 'NH',
    capital: 'Port Vila',
    continentName: 'Oceania',
    areaInSqKm: '12200.0',
  },
  {
    mainLanguages: 'French',
    sayHello: 'Salut',
    countryCode: 'WF',
    countryName: 'Wallis and Futuna',
    currencyCode: 'XPF',
    population: '16025',
    fipsCode: 'WF',
    capital: 'Mata-Utu',
    continentName: 'Oceania',
    areaInSqKm: '274.0',
  },
  {
    mainLanguages: 'Samoan, English',
    sayHello: 'Samoan: Talofa / Falopa | English: Hello',
    countryCode: 'WS',
    countryName: 'Samoa',
    currencyCode: 'WST',
    population: '192001',
    fipsCode: 'WS',
    capital: 'Apia',
    continentName: 'Oceania',
    areaInSqKm: '2944.0',
  },
  {
    mainLanguages: 'Albanian, Serbian',
    sayHello: 'Albanian: Fâla | Serbian: Zdravo',
    countryCode: 'XK',
    countryName: 'Kosovo',
    currencyCode: 'EUR',
    population: '1800000',
    fipsCode: 'KV',
    capital: 'Pristina',
    continentName: 'Europe',
    areaInSqKm: '10908.0',
  },
  {
    mainLanguages: 'Arabic',
    sayHello: 'Salam',
    countryCode: 'YE',
    countryName: 'Yemen',
    currencyCode: 'YER',
    population: '23495361',
    fipsCode: 'YM',
    capital: 'Sanaa',
    continentName: 'Asia',
    areaInSqKm: '527970.0',
  },
  {
    mainLanguages: 'French',
    sayHello: 'Salut',
    countryCode: 'YT',
    countryName: 'Mayotte',
    currencyCode: 'EUR',
    population: '159042',
    fipsCode: 'MF',
    capital: 'Mamoudzou',
    continentName: 'Africa',
    areaInSqKm: '374.0',
  },
  {
    mainLanguages: 'IsiZulu, IsiXhosa, Afrikaans',
    sayHello: 'IsiZulu: Sawubona | IsiXhosa: Molo | Afrikaans: Hallo',
    countryCode: 'ZA',
    countryName: 'South Africa',
    currencyCode: 'ZAR',
    population: '49000000',
    fipsCode: 'SF',
    capital: 'Pretoria',
    continentName: 'Africa',
    areaInSqKm: '1219912.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'ZM',
    countryName: 'Zambia',
    currencyCode: 'ZMW',
    population: '13460305',
    fipsCode: 'ZA',
    capital: 'Lusaka',
    continentName: 'Africa',
    areaInSqKm: '752614.0',
  },
  {
    mainLanguages: 'English',
    sayHello: 'Hello',
    countryCode: 'ZW',
    countryName: 'Zimbabwe',
    currencyCode: 'ZWL',
    population: '11651858',
    fipsCode: 'ZI',
    capital: 'Harare',
    continentName: 'Africa',
    areaInSqKm: '390580.0',
  },
];
export default hello;
